### PR TITLE
View form separation

### LINKED ISSUE #21: Change many if statements for forms to separate views

### LINKED ISSUE #34: Change methods that use cookies to return cookies

### PR DESCRIPTION
**Pull request by dandeduck**

### CODE REVIEW

**Comment by tomtzook** [comment]
So I might have missed this in another PR, but you have a problem with `order_edit.html` `Edit` button:
```
href="/partner/{{partner.name}}/{{order.id}}/{{package.id}}/">
```

This url doesn't exist in paths.

**Comment by tomtzook** [comment]
Why do we even need the "save later" mechanism? Why not save changes every time a change is made?

**Comment by tomtzook** [comment]
Problem: create a new package and then do: `update` on it before doing the `save changes`. We'll not work because `update` searches for it in the database but it isn't there.

**Review by tomtzook — COMMENTED** [review]
Let's discuss the touched feature first. See above comments.

**Comment by dandeduck** [comment]
> 
> 
> So I might have missed this in another PR, but you have a problem with `order_edit.html` `Edit` button:
> 
> ```
> href="/partner/{{partner.name}}/{{order.id}}/{{package.id}}/">
> ```
> 
> This url doesn't exist in paths.

I am aware of this, there is an issue regarding this #31  I just don't want to fix it until I switch to the autofill field since there will be some repetition

**Comment by dandeduck** [comment]
> 
> 
> Why do we even need the "save later" mechanism? Why not save changes every time a change is made?

Because we need to send an email when there is an update, you proposed to do it this way

**Comment by dandeduck** [comment]
> 
> 
> Problem: create a new package and then do: `update` on it before doing the `save changes`. We'll not work because `update` searches for it in the database but it isn't there.

I am aware of this, but I figured that it won't cause many problems since this button is visible only for staff, and they won't usually create packages. Additionally, it's kinda common sense that you can't update something which isn't saved. (what about editing a package that hasn't been saved yet? might be a problem when I fix this button) 

Because of above mentioned reasons and the added complexity of implementing this I figured not to. If you think otherwise then I suppose I would

**Comment by tomtzook** [comment]
> > Why do we even need the "save later" mechanism? Why not save changes every time a change is made?
> 
> Because we need to send an email when there is an update, you proposed to do it this way

But why are some changes not saved for later? `Update`/`revert` are saved immediately, while `new`/edit` are saved later? This inconsistency is not good. Choose one or the other; because for a user, the behavior of the site is not clear or straightforward.

**Comment by tomtzook** [comment]
> > Problem: create a new package and then do: `update` on it before doing the `save changes`. We'll not work because `update` searches for it in the database but it isn't there.
> 
> I am aware of this, but I figured that it won't cause many problems since this button is visible only for staff, and they won't usually create packages. Additionally, it's kinda common sense that you can't update something which isn't saved. (what about editing a package that hasn't been saved yet? might be a problem when I fix this button)
> 
> Because of above mentioned reasons and the added complexity of implementing this I figured not to. If you think otherwise then I suppose I would

Yet it still causes internal server errors? Plus how is the user supposed to know this isn't supported? The buttons are right there are clickable. They'll just use them and see an internal error response and assume there's some bug.

Either support it, or explicitly don't.

**Comment by dandeduck** [comment]
> > > Why do we even need the "save later" mechanism? Why not save changes every time a change is made?
> > 
> > Because we need to send an email when there is an update, you proposed to do it this way
> 
> But why are some changes not saved for later? `Update`/`revert` are saved immediately, while `new`/edit` are saved later? This inconsistency is not good. Choose one or the other; because for a user, the behavior of the site is not clear or straightforward. 

omg we need to save so the staff will be notified, but we don't need to notify anyone about a status change. So it's more convenient for staff to have it update right away. THE USER DOESN'T SEE IT

**Comment by dandeduck** [comment]
> > > Problem: create a new package and then do: `update` on it before doing the `save changes`. We'll not work because `update` searches for it in the database but it isn't there.
> > 
> > I am aware of this, but I figured that it won't cause many problems since this button is visible only for staff, and they won't usually create packages. Additionally, it's kinda common sense that you can't update something which isn't saved. (what about editing a package that hasn't been saved yet? might be a problem when I fix this button)
> > 
> > Because of above mentioned reasons and the added complexity of implementing this I figured not to. If you think otherwise then I suppose I would
> 
> Yet it still causes internal server errors? Plus how is the user supposed to know this isn't supported? The buttons are right there are clickable. They'll just use them and see an internal error response and assume there's some bug.
> 
> Either support it, or explicitly don't. 

ok I can disable or remove in this context jeez

**Comment by tomtzook** [comment]
> > > > Why do we even need the "save later" mechanism? Why not save changes every time a change is made?
> > > 
> > > 
> > > Because we need to send an email when there is an update, you proposed to do it this way
> > 
> > 
> > But why are some changes not saved for later? `Update`/`revert` are saved immediately, while `new`/edit` are saved later? This inconsistency is not good. Choose one or the other; because for a user, the behavior of the site is not clear or straightforward.
> 
> omg we need to save so the staff will be notified, but we don't need to notify anyone about a status change. So it's more convenient for staff to have it update right away. THE USER DOESN'T SEE IT

_user_ = user of software, i.e. not developer. That includes _staff_.
It's pretty weird in terms of behavior, since its two separate behaviors happening for a functionality that seems to be linked.

 But if that's what you want.. As long as it works and doesn't cause bugs I guess I fine with it.

**Comment by tomtzook** [comment]
> > > > Problem: create a new package and then do: `update` on it before doing the `save changes`. We'll not work because `update` searches for it in the database but it isn't there.
> > > 
> > > 
> > > I am aware of this, but I figured that it won't cause many problems since this button is visible only for staff, and they won't usually create packages. Additionally, it's kinda common sense that you can't update something which isn't saved. (what about editing a package that hasn't been saved yet? might be a problem when I fix this button)
> > > Because of above mentioned reasons and the added complexity of implementing this I figured not to. If you think otherwise then I suppose I would
> > 
> > 
> > Yet it still causes internal server errors? Plus how is the user supposed to know this isn't supported? The buttons are right there are clickable. They'll just use them and see an internal error response and assume there's some bug.
> > Either support it, or explicitly don't.
> 
> ok I can disable or remove in this context jeez

I'll approve after you do.

**Review by tomtzook — APPROVED** [review]
The separation is fine. That stuff we talked about can go in another branch

**Comment by tomtzook** [comment]
@dandeduck Merge at your convenience

**Comment by dandeduck** [comment]
> > > > > Why do we even need the "save later" mechanism? Why not save changes every time a change is made?
> > > > 
> > > > 
> > > > Because we need to send an email when there is an update, you proposed to do it this way
> > > 
> > > 
> > > But why are some changes not saved for later? `Update`/`revert` are saved immediately, while `new`/edit` are saved later? This inconsistency is not good. Choose one or the other; because for a user, the behavior of the site is not clear or straightforward.
> > 
> > omg we need to save so the staff will be notified, but we don't need to notify anyone about a status change. So it's more convenient for staff to have it update right away. THE USER DOESN'T SEE IT
> 
> _user_ = user of software, i.e. not developer. That includes _staff_.
> It's pretty weird in terms of behavior, since its two separate behaviors happening for a functionality that seems to be linked.
> 
>  But if that's what you want.. As long as it works and doesn't cause bugs I guess I fine with it.

I knew you would say that. I figured it's worth to sacrifice some clarity for easy of use for staff. I meant to say that they are less picky and I can explain to them stuff directly, it doesn't have to be so user friendly

**Comment by dandeduck** [comment]
> @dandeduck Merge at your convenience

ok thanks

**Comment by dandeduck** [comment]
Did you look at all the sumbited changes? just making sure, because I also did some bug fixing from the previous PR @tomtzook

**Comment by tomtzook** [comment]
> Did you look at all the sumbited changes? just making sure, because I also did some bug fixing from the previous PR @tomtzook

I might have missed it then. Happens

**Pull request merged**
